#!/bin/bash
# info system

#############constante

Title="kali info system"
jj="$(date +"%x %r %z")"
mj="mise à jour $jj sur $USER"

#########fonction

info_syst()
{
	echo "Information sur le système "
	uname -a
	free -m
	df -h
}

info_disk()
{
	echo " Information sur le disk "
	lsblk
}

info_chemin()
{
	echo "Information sur le chemin $PATH"
}

info_show_time()
{
	echo " Information sur la date"
	uptime
}


#########main

cat <<_EOF_

<html><head>
<title>$Title</title>
</head>
<body>
<h1>$Title</h1>

<p> $mj  </p>

<p> $(info_syst) </p>

<P> $(info_disk) </p>

<p> $(info_chemin) </p>

<p> $(info_show_time) </p>

</body>
</html>

_EOF_
