#!/bin/bash
# info system

###########constante
Title="kali Info System"
jj="$(date +"%x %r %z")"
mj="mise à jour $jj sur $USER"

#########fonction

info_user()
{
	echo "fonction sur information utilisateur"
}

info_disk()
{
	echo "fonction sur information sur le disk"
}

info_chemin()
{
	echo "fonction sur information sur les variables d'environnements"
}

info_show_time()
{
	echo "fonction sur information concernant le temps"
}




#########main

cat <<_EOF_
 <html>
 <head>
<title>$Title </title>
 </head>
<body>
<h1>$Title</h1>

<p> $mj </p>

$(info_user)
$(info_disk)
$(info_chemin)
$(info_show_time)


 </body>
</html>
_EOF_



