#!/bin/bash 
### -x ### 
##### on peut metrre <<set  -x>> au debut et à la fin <<set +x>> ###

echo "#########################"
echo " ## ./scriptcorrection ##"
echo " ## correction git     ##"

repo_url=https://github.com/Ghozen/Moussouris-Ghozen.git
###############main

echo -n "Entrer un message commit > "
if read -t 30 commitmessage; then
	echo " \nvous êtes rapide"
else 
	echo "vous êtes lent"
	exit 0
fi

read -p "repo github username > " user
echo " github username=$user "

if [ -d .git ];then

     echo "Dépot déja initialisé"
     echo " Push encours de demarrage "
       git add .
       git commit -m "$commitmessage"
       git push
else

     echo "Initialisation du repo"
       git init
       git add .
       git commit -m $commitmessage
       git branch -M main
       git remote add $repo_url
       git push -u origin main
fi
